### ISSUE TITLE
don't change to brackets in github issue

### ISSUE THREAD

**Issue by azzamsa** [rexim/org-cliplink#100]
org-cliplink change `[]` to `{}` when grabbing link+title from github issue 

Thanks for org-cliplink.

**Comment by rexim** [comment]
@azzamsa This is by design, because the syntax of an org-mode link is `[[link][title]]` and if the title contains `[]` it will break the org-mode parsing. Try this out:

1. Create new buffer: `C-x b temp RET`
2. Ensure it's in text mode: `M-x text-mode RET`
3. Type `[[link][[title]]]`
4. Switch to Org Mode: `M-x org-mode RET`

Observe that Org Mode cannot parse the link.

Even Org Mode itself is aware of this problem, because the command `org-insert-link` replaces `[]` with `{}` too. Try this out:

1. Create new buffer: `C-x b temp RET`
2. Switch to Org Mode: `M-x org-mode`
3. Insert a link: `M-x org-insert-link`
   - Set Link to `link`
   - Set Description to `[title]`

Observe that instead of `[[link][[title]]]` Org Mode inserted `[[link][{title}]]`.

So, I just reused the solution that the Org Mode Developers themselves came up with. :) Feels free to suggest a better solution.

**Comment by azzamsa** [comment]
Hi Kutepov.

> if the title contains [] it breaks the org-mode parsing

TIL

Thank you so much for your complete description toward the issue.

---

I want to say thanks.

Long time ago I used `copy-as-org` to copy link+title to my org buffers. I do this hundreds times a day. Bad news happened when the author doesn't have a time to port this extension to ff quantum. I end up making [my own](https://github.com/azzamsa/emacs.d/blob/master/modes/make-md-to-org.el) lisp function to handle this.

But with org-cliplink. It can be faster and easier. Also, it can cut long title with dots, which is very awesome.

Thanks lot for org-cliplink.
