### ISSUE TITLE
use org-cliplink in org-mode capture

### ISSUE THREAD

**Issue by zeltak** [rexim/org-cliplink#74]
Hi!

Just discovered org-cliplink and its amazing, i wanted something like this for a long time, thx so much!

i would love to incorperate this into my org-mode capture as i save all my bookmarks in an org-mode file. i tried using a capture template with an elisp function:
```
("K" "Bookmarks" entry (file+headline "/home/zeltak/org/files/web/wbookmarks.org" "bookmarks")
	   "* %(org-cliplink) \n:PROPERTIES:\n:CREATED: %U\n:END:\n " :empty-lines 1)
```
i get the following error
* later [#C] %![Error: (error Bad url: %0A(%22k%22%20%22Bookmarks%22%20entry%20(file+headline%20%22/home/zeltak/org/files/web/wbookmarks.org%22%20%22bookmarks%22)%0A%09%20%20%20%22*%20%x%20%5Cn:PROPERTIES:%5Cn:CREATED:%20%U%5Cn:END:%5Cn%20%22%20:empty-lines%201)%0A)]
   :PROPERTIES:
   :CREATED:  [2015-12-29 Tue 15:46]
   :END:

and the messages error:

```

Error running timer `org-element--cache-sync': (wrong-type-argument integer-or-marker-p nil)
url-retrieve-internal: Bad url: **%20%20%?%0A%20%5B%5Bid:2bf19d27-a0af-4e4c-91f1-9723a2dedf18%5D%5BCapture%20templates%5D%5D%0A%0A%20%20Note:%0A%0A**%20%20%3C2015-12-29%20Tue%2015:35%3E%0A***%20%20%0A%20%20%20%20:PROPERTIES:%0A%20%20%20%20:CREATED:%20%20%5B2015-12-29%20Tue%2015:34%5D%0A%20%20%20%20:END:%0A%20%20%20**%20**%20(file+headline%20%22/home/zeltak/org/files/web/wbookmarks.org%22%20%22bookmarks%22)%20%20%20Sourced:%20%5B2015-12-29%20Tue%5D%0A%0A%20%20%20%20%20%20Sourced:%20%5B2015-12-29%20Tue%5D%0A%0A%20%5B%5Bid:2bf19d27-a0af-4e4c-91f1-9723a2dedf18%5D%5BCapture%20templates%5D%5D%0A%0A%20%20Note:%0A%0A**%20%20%3C2015-12-29%20Tue%2015:34%3E%0A***%20(file+headline%20%22/home/zeltak/org/files/web/wbookmarks.org%22%20%22bookmarks%22)%20%20%20Sourced:%20%5B2015-12-29%20Tue%5D%0A%0A%20%5B%5Bid:2bf19d27-a0af-4e4c-91f1-9723a2dedf18%5D%5BCapture%20templates%5D%5D%0A%0A%20%20Note:%0A%0A**%20%20%3C2015-12-29%20Tue%2015:33%3E%0A%20(file+headline%20%22/home/zeltak/org/files/web/wbookmarks.org%22%20%22bookmarks%22)%5B%5Bid:2bf19d27-a0af-4e4c-91f1-9723a2dedf18%5D%5BCapture%20templates%5D%5D%0A%0A%20%20Note:%0A%0A**%20%20%3C2015-12-29%20Tue%2015:30%3E%0A%20http://kitchingroup.cheme.cmu.edu/blog/2015/11/25/LDAP-lookups-from-Emacs/%0A%0A%20%20Note:%0A%0A**%20%20%3C2015-12-29%20Tue%2015:27%3E%0A%20$Note-if%20you%20see%20starnge%20behivour%20this%20maybe%20a%20culprit$%20%20%0A%20%5B%5Bid:442b10d2-cd02-44c6-b180-e2ac32aa8c59%5D%5B1info%5D%5D%0A%0A%20%20Note:%0A%0A**%20BOOKMARKS%20%3C2015-12-29%20Tue%2009:05%3E%0A%20http://pragmaticemacs.com/emacs/master-your-inbox-with-mu4e-and-org-mode/%5B%5Bid:2bf19d27-a0af-4e4c-91f1-9723a2dedf18%5D%5BCapture%20templates%5D%5D%0A%0A%20%20Note:%0A
Error running timer `org-element--cache-sync': (wrong-type-argument integer-or-marker-p nil) [2 times]
Contacting host: github.com:443
```
if i swap the  %(org-cliplink) with %x and run org-cliplink manually it works like a charm

any idea whats going on?

best

Z

**Comment by rexim** [comment]
Hello Z,

Unfortunately, the `org-cliplink` function doesn't work like that. In your case org-capture expected `org-cliplink` function to return something. But `org-cliplink` doesn't actually return anything at all. :) It just makes an asynchronous request to the server, and once the response is retrieved inserts the result to the current position of the current buffer.

I knew about this problem and even created an issue #51. But didn't have enough motivation to work on that until now. :) So, thank you very much for filing this!

I've just implemented `org-cliplink-capture` function for you that does synchronous request and returns the result instead of inserting it. So, grab the latest org-cliplink, replace `%(org-cliplink)` with `%(org-cliplink-capture)` and see if it works for you! :)

**Comment by zeltak** [comment]
thx so much!

works like a charm now, loving org-cliplink :)

thx again

best

Z
